export const Check = {
    CHECK_LOGIN : 'CHECK_LOGIN'
}
export const UPDATE = 'UPDATE';

export const RESET_STORE = 'RESET_STORE';

export const REHYDRATE = 'persist/REHYDRATE';

export const Notifications = {
    ADD_NOTIFICATION :'ADD_NOTIFICATION',
    REMOVE_NOTIFICATION: 'REMOVE_NOTIFICATION',
    CLEAR_NOTIFICATION: 'CLEAR_NOTIFICATION'
}

export const AppState = {
    CHANGE_APP_STATE : 'CHANGE_APP_STATE',
    CHANGE_ROOT : 'CHANGE_ROOT',
    CHANGE_ORIENTATION : 'CHANGE_ORIENTATION'
}